name: Trigger auto deployment for rcb-web

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/rcb-web-AutoDeployTrigger-21d23ae9-d77f-43e8-83cf-46d831d156e5.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.RCBWEB_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: unique1.azurecr.io
          registryUsername: ${{ secrets.RCBWEB_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.RCBWEB_REGISTRY_PASSWORD }}
          containerAppName: rcb-web
          resourceGroup: resource
          imageToBuild: unique1.azurecr.io/rcb-web:${{ github.sha }}
          
            

     

